image: gitpod/workspace-full

tasks:
  - name: Clone repositórios
    init: |
      if [ ! -d "frontend" ]; then
        git clone https://github.com/carlinhoshk/frontend-projetoCAP.git frontend
      fi
      if [ ! -d "backend" ]; then
        git clone https://github.com/carlinhoshk/CAP.git backend
      fi
  - name: Subir ambiente Docker Compose
    command: |
      docker compose -f docker-compose.gitpod.yml up --build -d

ports:
  - port: 3000
    onOpen: open-preview
  - port: 8080
    onOpen: open-browser