image: gitpod/workspace-full

ports:
  - port: 9090
    onOpen: open-preview
  - port: 8080
    onOpen: open-preview
  - port: 3306

tasks:
  - name: Start MariaDB
    command: |
      docker-compose -f docker-compose.gitpod.yml up -d
    init: |
      echo "Iniciando banco de dados MariaDB..."
  - name: Start Backend
    command: |
      cd backend && ./mvnw spring-boot:run
    init: |
      echo "Iniciando backend Spring Boot..."
  - name: Start Frontend
    command: |
      cd frontend && npx ng serve --host 0.0.0.0 --port 8080
    init: |
      echo "Iniciando frontend Angular..."

vscode:
  extensions:
    - vscjava.vscode-java-pack
    - angular.ng-template
    - dbaeumer.vscode-eslint
    - esbenp.prettier-vscode
    - ms-azuretools.vscode-docker