version: '3.8'
services:
  backend:
    image: carlinhoshk/escola-app:latest
    container_name: escola_backend
    environment:
      SPRING_DATASOURCE_URL: jdbc:mariadb://mariadb:3306/escola
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
      SPRING_FLYWAY_ENABLED: true
      SPRING_FLYWAY_URL: jdbc:mariadb://mariadb:3306/escola
      SPRING_FLYWAY_USER: user
      SPRING_FLYWAY_PASSWORD: password
      SPRING_PROFILES_ACTIVE: prod
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:+UseG1GC -XX:MaxGCPauseMillis=200"
    depends_on:
      mariadb:
        condition: service_healthy
    networks:
      - app-network
    ports:
      - "9090:9090"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1.5G
        reservations:
          cpus: '0.5'
          memory: 512M

  frontend:
    image: carlinhoshk/escola-frontend:latest
    container_name: escola_frontend
    networks:
      - app-network
    ports:
      - "4200:4200"
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          cpus: '0.2'
          memory: 256M

  mariadb:
    image: mariadb:10.11
    container_name: escola_db
    environment:
      MARIADB_ROOT_PASSWORD: root
      MARIADB_DATABASE: escola
      MARIADB_USER: user
      MARIADB_PASSWORD: password
      MARIADB_INNODB_BUFFER_POOL_SIZE: 512M
      MARIADB_MAX_CONNECTIONS: 50
      MARIADB_INNODB_LOG_FILE_SIZE: 64M
      MARIADB_INNODB_FLUSH_LOG_AT_TRX_COMMIT: 2
      MARIADB_INNODB_FLUSH_METHOD: O_DIRECT
    ports:
      - "3306:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci --innodb-buffer-pool-size=512M --innodb-log-file-size=64M --innodb-flush-log-at-trx-commit=2 --innodb-flush-method=O_DIRECT
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "user", "-ppassword"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

networks:
  app-network:
    driver: bridge

volumes:
  mariadb_data: 